---
- name: Install/Configure k3s Prerequisites
  gather_facts: true
  hosts:
    - k3s_agents
    - k3s_servers
  become: true
  roles:
    - k3s.orchestration.prereq

- name: Install/Configure k3s Server Nodes
  hosts: k3s_servers
  become: true
  roles:
    - k3s.orchestration.k3s_server

- name: Install/Configure k3s Agent Nodes
  hosts: k3s_agents
  become: true
  roles:
    - k3s.orchestration.k3s_agent
