---
- name: Install k3s Prerequisites
  hosts:
    - agent
    - server
  tags:
    - k3s-prereq
  become: true
  roles:
    - role: k3s.orchestration.prereq

- name: Install k3s Server Nodes
  hosts: server
  tags: [k3s-server]
  become: true
  roles:
    - role: k3s.orchestration.k3s_server

- name: Install k3s Agent Nodes
  hosts: agent
  tags: [k3s-agents]
  become: true
  roles:
    - role: k3s.orchestration.k3s_agent

- name: Upgrade k3s Version
  hosts:
    - agent
    - server
  tags:
    - k3s-upgrade
  become: true
  roles:
    - role: k3s.orchestration.k3s_upgrade
