---
k3s_version: v1.30.0+k3s1

api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"

extra_server_args: "--disable=traefik --disable=servicelb"
extra_agent_args: ""

extra_manifests: [ 'manifests/kube-vip/rbac.yaml', 'manifests/kube-vip/daemonset.yaml']
